apiVersion: v1
entries:
  lustre-csi-driver:
  - apiVersion: v2
    appVersion: 0.1.11
    created: "2026-04-30T16:02:30.319938329+02:00"
    description: Container Storage Interface (CSI) driver for static provisioning
      of Lustre filesystems
    digest: 24929e0ec94f802be18070f323003d1f27ff15c2c540b8a450e69b9cd5171bf0
    home: https://github.com/HewlettPackard/lustre-csi-driver
    keywords:
    - lustre
    - lustre-fs
    - lustre-csi
    name: lustre-csi-driver
    type: application
    urls:
    - https://raw.githubusercontent.com/AdelKS/lustre-csi-driver/chart-restructure/charts/v0.1.11/lustre-csi-driver-0.1.11.tgz
    version: 0.1.11
generated: "2026-04-30T16:02:30.319091814+02:00"
